app:
  test: 777
  scheduler:
    interval: 2000

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

github-client:
  base-url: https://api.github.com
  api-version: 2022-11-28

stackoverflow-client:
  base-url: https://api/stackexchange.com/2.3